### ISSUE TITLE
✅ Homework Feedback #3

### ISSUE THREAD

**Issue by cmota** [Ernestico98/M14-mobile-dev#1]
Hello 👋,

Let me start by saying that I really liked that you dive-in directly in Compose to do this exercise 🙌. 

The UI is perfect! And the pictures that you've selected for the main screen even better 😻.

I've explored a bit your repository and I have to say that everything is well organized, and, your readme file with the project images create a great first impression - well done!

Keep up with the good work! 🙌

### Grade

100/100

### Suggestions for improvement

I'm going to write a couple of suggestions for improvement, but don't worry, these are really minor 🙂 

* Looking at the imports on your **DetailView.kt** I'm seeing that some are not used in the project. When an import is not used, Android Studio changes its color to grey. Although, this doesn't have any impact on your code, it's always a good approach to only have the ones that you're using declared.

* I would move the `Homework1Theme` declaration from being inside `Screen` to be after `setContent`. Since `Screen` is already drawing the screen, I would make this separation

* When you declare a **Composable** and don't define any property - for instance, `Box` on line 63 - you can remove the parenthesis, since they're not doing anything on the code. This is also valid for when you create your `Cat` class where the brackets aren't needed.

* The **Cat** class is not wrong, but typically in Kotlin we use **data classes** when we want to define a POJO. They are optimized to hold data.

* You've declared variables as `var` when you can declare them as `val`. For instance, on line 40,  `cats` is declared as `var` and its value never changes. In this scenarios, you should declare them as `val`. Remember that `val` means **value** (=immutable)  and `var` **variable** (=variable).

* Empty spaces are great to separate different functions, but I've noticed that you've had some extras at the end of the file. It's a really, really, minor comment, but having everything organized give it a different look.

**Comment by Ernestico98** [comment]
Thank you very much for your valuable feedback, I'll take it into account for the upcoming tasks.
